name: Release a new version

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4 # v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-musl
      - name: Install dependency
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends musl-tools upx
      - name: Compile
        run: cargo build --release --locked --all-features --target x86_64-unknown-linux-musl
      - name: Compress
        run: upx --lzma target/x86_64-unknown-linux-musl/release/archlinuxcn-packages
      - name: Setup go
        uses: https://github.com/actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639 # v4
        with:
          go-version: '>=1.20.1'
      - name: Release
        uses: https://gitea.com/actions/release-action@21a5938ff2548f6472d89ba13b3cdd8af4c67068 # main
        with:
          files: |-
            target/x86_64-unknown-linux-musl/release/archlinuxcn-packages
          api_key: ${{ secrets.IMLONGHAO_BOT_TOKEN }}
